export const FETCHING_QUOTES = "FETCHING_QUOTES";
export const QUOTES_FETCHED_SUCCESS = "QUOTES_FETCHED_SUCCESS";
export const QUOTES_FETCH_FAILED = "QUOTES_FETCH_FAILED";
export const SEARCHING_QUOTES = "SEARCH_USER";
export const SEARCHING_QUOTES_COMPLETE = "SEARCHING_QUOTES_COMPLETE";
export const PIN_QUOTES = "PIN_QUOTES";
