export const FETCHING_USER = "FETCHING_USER";
export const USER_FETCHED_SUCCESS = "USER_FETCHED_SUCCESS";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
export const FETCHING_PROFILES = "FETCHING_PROFILES";
