export const FETCHING_USER = "FETCHING_USER";
export const USER_FETCHED_SUCCESS = "USER_FETCHED_SUCCESS";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";
export const FETCHING_PROFILES = "FETCHING_PROFILES";
export const SEARCHING_USER = "SEARCH_USER";
export const SEARCHING_USER_COMPLETE = "SEARCHING_USER_COMPLETE";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
